### ISSUE TITLE
The sample application seems not to exist anymore on github. Please update this tutorial accordingly

### ISSUE THREAD

**Issue by uwitzig** [ibm-cloud-docs/messages-for-rabbitmq#2] opened 2020-03-25 11:37 UTC

**Comment by DailyAlice** [comment] 2020-04-02 19:58
Both the sample applications in the docs do still exist.

The sample application for the [K8 tutorial](https://cloud.ibm.com/docs/services/messages-for-rabbitmq?topic=cloud-databases-tutorial-k8s-app) is in Github [here](https://github.com/IBM-Cloud/clouddatabases-helloworld-kubernetes-examples).

The sample application for the [Getting Started tutorial](https://cloud.ibm.com/docs/services/messages-for-rabbitmq?topic=messages-for-rabbitmq-getting-started) is in Github [here](https://github.com/IBM-Cloud/clouddatabases-helloworld-cloudfoundry-examples/tree/node/rabbitmq).

All the links appear to be live and working. I can't reproduce the problem you are having. Closing.

**Closed by DailyAlice** 2020-04-02 19:58 UTC

**Comment by uwitzig** [comment] 2020-04-03 13:40
The cloudfoundry example is not working. The main.js file as documented in the README.md is missing.

https://github.com/IBM-Cloud/clouddatabases-helloworld-cloudfoundry-examples/tree/node/rabbitmq
